# -*- coding: utf-8 -*-
"""NLTK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fCHBlsKvIMCEY2RlkLHGzu1Y_YbKkGEb
"""

!pip install nltk
import nltk
nltk.download('punkt')

import nltk
from nltk.tokenize import word_tokenize

def tokenize_text(text):
    tokens = word_tokenize(text)
    return tokens

!pip install flask

from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route('/process_text', methods=['POST'])
def process_text():
    data = request.get_json()
    text = data.get('text')
    if text:
        # Call your NLTK processing function here
        tokens = tokenize_text(text)
        return jsonify({'tokens': tokens})
    else:
        return jsonify({'error': 'Invalid request'}), 400

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)

!pip install pyngrok
from pyngrok import ngrok

public_url = ngrok.connect(port=5000)
print("Public URL:", public_url)
